### ISSUE TITLE
CREST fmriprep: node and OS error

### ISSUE THREAD

**Issue by ariveradompenciel** [HBClab/SoftwareIssues#12] opened 2020-04-09 14:31 UTC
### Script/Job File

```
#!/bin/bash

#$ -pe smp 16
#$ -q UI
#$ -m bea
#$ -M adriana-rivera-dompenciel@uiowa.edu
#$ -o /Shared/vosslabhpc/Projects/CREST/code/fmriprep/out/
#$ -e /Shared/vosslabhpc/Projects/CREST/code/fmriprep/err/
OMP_NUM_THREADS=10
singularity run -H ${HOME}/singularity_home -B /Shared/vosslabhpc:/mnt \
/Shared/vosslabhpc/UniversalSoftware/SingularityContainers/fmriprep-1.2.1.simg \
/mnt/Projects/CREST/ /mnt/Projects/CREST/derivatives \
participant --participant_label OPTIMA4060 \
-w /nfsscratch/Users/ariveradompenciel/work/CRESTfmriprep \
--write-graph --mem_mb 35000 --omp-nthreads 10 --nthreads 16 --use-aroma \
--output-space template \
--template MNI152NLin2009cAsym \
--fs-license-file /mnt/UniversalSoftware/freesurfer_license.txt
```

### Email Message

```
Job 9534819 (sub-OPTIMA4060.job) Complete
User             = ariveradompenciel
Queue            = UI@argon-itf-cf45-27.hpc
Host             = argon-itf-cf45-27.hpc
Start Time       = 04/08/2020 18:16:26
End Time         = 04/08/2020 18:33:28
User Time        = 00:00:51
System Time      = 00:00:02
Wallclock Time   = 00:17:02
CPU              = 01:34:11
Max vmem         = 5.240G
Exit Status      = 1
```

### Output File

```
200408-18:16:36,785 nipype.workflow IMPORTANT:
	 
    Running fMRIPREP version 1.2.1:
      * BIDS dataset path: /mnt/Projects/CREST.
      * Participant list: ['OPTIMA4060'].
      * Run identifier: 20200408-181636_935ebc88-48a6-4645-b4ca-5a561586e29c.
    
200408-18:16:36,785 nipype.workflow WARNING:
	 Option --debug is deprecated and has no effect
200408-18:16:43,663 nipype.workflow IMPORTANT:
	 Creating bold processing workflow for "/mnt/Projects/CREST/sub-OPTIMA4060/func/sub-OPTIMA4060_task-rest_bold.nii.gz" (0.03 GB / 180 TRs). Memory resampled/largemem=0.12/0.17 GB.
200408-18:16:43,697 nipype.workflow IMPORTANT:
	 No single-band-reference found for sub-OPTIMA4060_task-rest_bold.nii.gz
200408-18:16:44,148 nipype.workflow WARNING:
	 SDC: no fieldmaps found or they were ignored (/mnt/Projects/CREST/sub-OPTIMA4060/func/sub-OPTIMA4060_task-rest_bold.nii.gz).
200408-18:16:49,196 nipype.workflow IMPORTANT:
	 Works derived from this fMRIPrep execution should include the following boilerplate:


Results included in this manuscript come from preprocessing
performed using *fMRIPprep* 1.2.1
(@fmriprep1; @fmriprep2; RRID:SCR_016216),
which is based on *Nipype* 1.1.4
(@nipype1; @nipype2; RRID:SCR_002502).

Anatomical data preprocessing

: The T1-weighted (T1w) image was corrected for intensity non-uniformity (INU)
using `N4BiasFieldCorrection` [@n4, ANTs 2.2.0],
and used as T1w-reference throughout the workflow.
The T1w-reference was then skull-stripped using `antsBrainExtraction.sh`
(ANTs 2.2.0), using OASIS as target template.
Brain surfaces were reconstructed using `recon-all` [FreeSurfer 6.0.1,
RRID:SCR_001847, @fs_reconall], and the brain mask estimated
previously was refined with a custom variation of the method to reconcile
ANTs-derived and FreeSurfer-derived segmentations of the cortical
gray-matter of Mindboggle [RRID:SCR_002438, @mindboggle].
Spatial normalization to the ICBM 152 Nonlinear Asymmetrical
template version 2009c [@mni, RRID:SCR_008796] was performed
through nonlinear registration with `antsRegistration`
[ANTs 2.2.0, RRID:SCR_004757, @ants], using
brain-extracted versions of both T1w volume and template.
Brain tissue segmentation of cerebrospinal fluid (CSF),
white-matter (WM) and gray-matter (GM) was performed on
the brain-extracted T1w using `fast` [FSL 5.0.9, RRID:SCR_002823,
@fsl_fast].


Functional data preprocessing

: For each of the 1 BOLD runs found per subject (across all
tasks and sessions), the following preprocessing was performed.
First, a reference volume and its skull-stripped version were generated
using a custom methodology of *fMRIPrep*.
The BOLD reference was then co-registered to the T1w reference using
`bbregister` (FreeSurfer) which implements boundary-based registration [@bbr].
Co-registration was configured with nine degrees of freedom to account
for distortions remaining in the BOLD reference.
Head-motion parameters with respect to the BOLD reference
(transformation matrices, and six corresponding rotation and translation
parameters) are estimated before any spatiotemporal filtering using
`mcflirt` [FSL 5.0.9, @mcflirt].
The BOLD time-series (including slice-timing correction when applied)
were resampled onto their original, native space by applying
a single, composite transform to correct for head-motion and
susceptibility distortions.
These resampled BOLD time-series will be referred to as *preprocessed
BOLD in original space*, or just *preprocessed BOLD*.
First, a reference volume and its skull-stripped version were generated
using a custom methodology of *fMRIPrep*.
Automatic removal of motion artifacts using independent component analysis
[ICA-AROMA, @aroma] was performed on the *preprocessed BOLD on MNI space*
time-series after removal of non-steady state volumes and spatial smoothing
with an isotropic, Gaussian kernel of 6mm FWHM (full-width half-maximum).
Corresponding "non-aggresively" denoised runs were produced after such
smoothing.
Additionally, the "aggressive" noise-regressors were collected and placed
in the corresponding confounds file.
The BOLD time-series were resampled to MNI152NLin2009cAsym standard space,
generating a *preprocessed BOLD run in MNI152NLin2009cAsym space*.
First, a reference volume and its skull-stripped version were generated
using a custom methodology of *fMRIPrep*.
Several confounding time-series were calculated based on the
*preprocessed BOLD*: framewise displacement (FD), DVARS and
three region-wise global signals.
FD and DVARS are calculated for each functional run, both using their
implementations in *Nipype* [following the definitions by @power_fd_dvars].
The three global signals are extracted within the CSF, the WM, and
the whole-brain masks.
Additionally, a set of physiological regressors were extracted to
allow for component-based noise correction [*CompCor*, @compcor].
Principal components are estimated after high-pass filtering the
*preprocessed BOLD* time-series (using a discrete cosine filter with
128s cut-off) for the two *CompCor* variants: temporal (tCompCor)
and anatomical (aCompCor).
Six tCompCor components are then calculated from the top 5% variable
voxels within a mask covering the subcortical regions.
This subcortical mask is obtained by heavily eroding the brain mask,
which ensures it does not include cortical GM regions.
For aCompCor, six components are calculated within the intersection of
the aforementioned mask and the union of CSF and WM masks calculated
in T1w space, after their projection to the native space of each
functional run (using the inverse BOLD-to-T1w transformation).
The head-motion estimates calculated in the correction step were also
placed within the corresponding confounds file.
All resamplings can be performed with *a single interpolation
step* by composing all the pertinent transformations (i.e. head-motion
transform matrices, susceptibility distortion correction when available,
and co-registrations to anatomical and template spaces).
Gridded (volumetric) resamplings were performed using `antsApplyTransforms` (ANTs),
configured with Lanczos interpolation to minimize the smoothing
effects of other kernels [@lanczos].
Non-gridded (surface) resamplings were performed using `mri_vol2surf`
(FreeSurfer).


Many internal operations of *fMRIPrep* use
*Nilearn* 0.4.2 [@nilearn, RRID:SCR_001362],
mostly within the functional processing workflow.
For more details of the pipeline, see [the section corresponding
to workflows in *fMRIPrep*'s documentation](https://fmriprep.readthedocs.io/en/latest/workflows.html "FMRIPrep's documentation").


### References


200408-18:17:04,713 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_OPTIMA4060_wf.func_preproc_task_rest_wf.bold_reference_wf.validate" in "/nfsscratch/Users/ariveradompenciel/work/CRESTfmriprep/fmriprep_wf/single_subject_OPTIMA4060_wf/func_preproc_task_rest_wf/bold_reference_wf/validate".
200408-18:17:04,731 nipype.workflow INFO:
	 [Node] Running "validate" ("fmriprep.interfaces.images.ValidateImage")
200408-18:17:04,764 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_OPTIMA4060_wf.func_preproc_task_rest_wf.bold_reference_wf.validate".
200408-18:17:04,869 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_OPTIMA4060_wf.bidssrc" in "/nfsscratch/Users/ariveradompenciel/work/CRESTfmriprep/fmriprep_wf/single_subject_OPTIMA4060_wf/bidssrc".
200408-18:17:04,883 nipype.workflow INFO:
	 [Node] Running "bidssrc" ("fmriprep.interfaces.bids.BIDSDataGrabber")
200408-18:17:04,885 nipype.interface WARNING:
	 No 't2w' images found for sub-<undefined>
200408-18:17:04,885 nipype.interface WARNING:
	 No 'flair' images found for sub-<undefined>
200408-18:17:04,885 nipype.interface WARNING:
	 No 'sbref' images found for sub-<undefined>
200408-18:17:04,885 nipype.interface WARNING:
	 No 'roi' images found for sub-<undefined>
200408-18:17:04,902 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_OPTIMA4060_wf.bidssrc".
200408-18:17:07,813 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_OPTIMA4060_wf.func_preproc_task_rest_wf.bold_split" in "/nfsscratch/Users/ariveradompenciel/work/CRESTfmriprep/fmriprep_wf/single_subject_OPTIMA4060_wf/func_preproc_task_rest_wf/bold_split".
200408-18:17:07,847 nipype.workflow INFO:
	 [Node] Running "bold_split" ("nipype.interfaces.fsl.utils.Split"), a CommandLine Interface with command:
fslsplit /mnt/Projects/CREST/sub-OPTIMA4060/func/sub-OPTIMA4060_task-rest_bold.nii.gz -t
200408-18:17:09,179 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_OPTIMA4060_wf.func_preproc_task_rest_wf.bold_reference_wf.gen_ref" in "/nfsscratch/Users/ariveradompenciel/work/CRESTfmriprep/fmriprep_wf/single_subject_OPTIMA4060_wf/func_preproc_task_rest_wf/bold_reference_wf/gen_ref".
200408-18:17:09,321 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_OPTIMA4060_wf.anat_preproc_wf.anat_template_wf.t1_template_dimensions" in "/nfsscratch/Users/ariveradompenciel/work/CRESTfmriprep/fmriprep_wf/single_subject_OPTIMA4060_wf/anat_preproc_wf/anat_template_wf/t1_template_dimensions".
200408-18:17:09,354 nipype.workflow INFO:
	 [Node] Running "gen_ref" ("niworkflows.interfaces.registration.EstimateReferenceImage")
200408-18:17:09,357 nipype.workflow INFO:
	 [Node] Running "t1_template_dimensions" ("fmriprep.interfaces.images.TemplateDimensions")
200408-18:17:09,892 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_OPTIMA4060_wf.anat_preproc_wf.anat_template_wf.t1_template_dimensions".
200408-18:17:10,868 nipype.interface INFO:
	 stderr 2020-04-08T18:17:10.868147:++ 3dvolreg: AFNI version=Debian-16.2.07~dfsg.1-5~nd16.04+1 (Jun 12 2017) [64-bit]
200408-18:17:10,868 nipype.interface INFO:
	 stderr 2020-04-08T18:17:10.868147:++ Authored by: RW Cox
200408-18:17:10,873 nipype.interface INFO:
	 stderr 2020-04-08T18:17:10.873247:++ Coarse del was 10, replaced with 3
200408-18:17:12,136 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_OPTIMA4060_wf.anat_preproc_wf.anat_derivatives_wf.t1_name" in "/nfsscratch/Users/ariveradompenciel/work/CRESTfmriprep/fmriprep_wf/single_subject_OPTIMA4060_wf/anat_preproc_wf/anat_derivatives_wf/t1_name".
200408-18:17:12,150 nipype.workflow INFO:
	 [Node] Running "t1_name" ("nipype.interfaces.utility.wrappers.Function")
200408-18:17:12,185 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_OPTIMA4060_wf.anat_preproc_wf.anat_derivatives_wf.t1_name".
200408-18:17:13,96 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_OPTIMA4060_wf.anat_preproc_wf.anat_template_wf.t1_conform" in "/nfsscratch/Users/ariveradompenciel/work/CRESTfmriprep/fmriprep_wf/single_subject_OPTIMA4060_wf/anat_preproc_wf/anat_template_wf/t1_conform".
200408-18:17:13,180 nipype.workflow INFO:
	 [Node] Setting-up "_t1_conform0" in "/nfsscratch/Users/ariveradompenciel/work/CRESTfmriprep/fmriprep_wf/single_subject_OPTIMA4060_wf/anat_preproc_wf/anat_template_wf/t1_conform/mapflow/_t1_conform0".
200408-18:17:13,217 nipype.workflow INFO:
	 [Node] Running "_t1_conform0" ("fmriprep.interfaces.images.Conform")
200408-18:17:14,204 nipype.workflow INFO:
	 [Node] Finished "_t1_conform0".
200408-18:17:14,214 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_OPTIMA4060_wf.anat_preproc_wf.anat_template_wf.t1_conform".
200408-18:17:15,795 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_OPTIMA4060_wf.anat_preproc_wf.skullstrip_ants_wf.t1_skull_strip" in "/nfsscratch/Users/ariveradompenciel/work/CRESTfmriprep/fmriprep_wf/single_subject_OPTIMA4060_wf/anat_preproc_wf/skullstrip_ants_wf/t1_skull_strip".
200408-18:17:15,833 nipype.workflow INFO:
	 [Node] Running "t1_skull_strip" ("nipype.interfaces.ants.segmentation.BrainExtraction"), a CommandLine Interface with command:
antsBrainExtraction.sh -a /nfsscratch/Users/ariveradompenciel/work/CRESTfmriprep/fmriprep_wf/single_subject_OPTIMA4060_wf/anat_preproc_wf/anat_template_wf/t1_conform/mapflow/_t1_conform0/sub-OPTIMA4060_T1w_ras.nii.gz -m /nfsscratch/Users/ariveradompenciel/work/CRESTfmriprep/fmriprep_wf/single_subject_OPTIMA4060_wf/anat_preproc_wf/skullstrip_ants_wf/t1_skull_strip/T_template0_BrainCerebellumProbabilityMask.nii.gz -e /niworkflows_data/ants_oasis_template_ras/T_template0.nii.gz -d 3 -f /niworkflows_data/ants_oasis_template_ras/T_template0_BrainCerebellumRegistrationMask.nii.gz -s nii.gz -k 1 -o highres001_ -q 1 -u 1
200408-18:17:16,789 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_OPTIMA4060_wf.anat_preproc_wf.surface_recon_wf.recon_config" in "/nfsscratch/Users/ariveradompenciel/work/CRESTfmriprep/fmriprep_wf/single_subject_OPTIMA4060_wf/anat_preproc_wf/surface_recon_wf/recon_config".
200408-18:17:16,814 nipype.workflow INFO:
	 [Node] Running "recon_config" ("fmriprep.interfaces.freesurfer.FSDetectInputs")
200408-18:17:16,858 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_OPTIMA4060_wf.anat_preproc_wf.surface_recon_wf.recon_config".
200408-18:17:22,541 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_OPTIMA4060_wf.func_preproc_task_rest_wf.bold_split".
200408-18:17:24,611 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_OPTIMA4060_wf.func_preproc_task_rest_wf.ica_aroma_wf.bold_mni_trans_wf.gen_ref" in "/nfsscratch/Users/ariveradompenciel/work/CRESTfmriprep/fmriprep_wf/single_subject_OPTIMA4060_wf/func_preproc_task_rest_wf/ica_aroma_wf/bold_mni_trans_wf/gen_ref".
200408-18:17:24,644 nipype.workflow INFO:
	 [Node] Running "gen_ref" ("niworkflows.interfaces.utils.GenerateSamplingReference")
200408-18:17:24,683 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_OPTIMA4060_wf.func_preproc_task_rest_wf.bold_mni_trans_wf.gen_ref" in "/nfsscratch/Users/ariveradompenciel/work/CRESTfmriprep/fmriprep_wf/single_subject_OPTIMA4060_wf/func_preproc_task_rest_wf/bold_mni_trans_wf/gen_ref".
200408-18:17:24,698 nipype.workflow INFO:
	 [Node] Running "gen_ref" ("niworkflows.interfaces.utils.GenerateSamplingReference")
200408-18:17:25,220 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_OPTIMA4060_wf.func_preproc_task_rest_wf.bold_mni_trans_wf.gen_ref".
200408-18:17:25,221 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_OPTIMA4060_wf.func_preproc_task_rest_wf.ica_aroma_wf.bold_mni_trans_wf.gen_ref".
200408-18:17:28,624 nipype.interface INFO:
	 stderr 2020-04-08T18:17:28.623999:++ Max displacement in automask = 0.48 (mm) at sub-brick 17
200408-18:17:28,624 nipype.interface INFO:
	 stderr 2020-04-08T18:17:28.623999:++ Max delta displ  in automask = 0.15 (mm) at sub-brick 18
200408-18:17:29,989 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_OPTIMA4060_wf.func_preproc_task_rest_wf.bold_reference_wf.gen_ref".
200408-18:17:32,863 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_OPTIMA4060_wf.func_preproc_task_rest_wf.bold_reference_wf.validate_ref" in "/nfsscratch/Users/ariveradompenciel/work/CRESTfmriprep/fmriprep_wf/single_subject_OPTIMA4060_wf/func_preproc_task_rest_wf/bold_reference_wf/validate_ref".
200408-18:17:32,878 nipype.workflow INFO:
	 [Node] Running "validate_ref" ("fmriprep.interfaces.images.ValidateImage")
200408-18:17:32,927 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_OPTIMA4060_wf.func_preproc_task_rest_wf.bold_reference_wf.validate_ref".
200408-18:17:35,928 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_OPTIMA4060_wf.func_preproc_task_rest_wf.bold_hmc_wf.mcflirt" in "/nfsscratch/Users/ariveradompenciel/work/CRESTfmriprep/fmriprep_wf/single_subject_OPTIMA4060_wf/func_preproc_task_rest_wf/bold_hmc_wf/mcflirt".
200408-18:17:35,947 nipype.workflow INFO:
	 [Node] Running "mcflirt" ("nipype.interfaces.fsl.preprocess.MCFLIRT"), a CommandLine Interface with command:
mcflirt -in /mnt/Projects/CREST/sub-OPTIMA4060/func/sub-OPTIMA4060_task-rest_bold.nii.gz -out /nfsscratch/Users/ariveradompenciel/work/CRESTfmriprep/fmriprep_wf/single_subject_OPTIMA4060_wf/func_preproc_task_rest_wf/bold_hmc_wf/mcflirt/sub-OPTIMA4060_task-rest_bold_mcf.nii.gz -reffile /nfsscratch/Users/ariveradompenciel/work/CRESTfmriprep/fmriprep_wf/single_subject_OPTIMA4060_wf/func_preproc_task_rest_wf/bold_reference_wf/gen_ref/ref_image.nii.gz -mats -plots
200408-18:18:16,970 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_OPTIMA4060_wf.func_preproc_task_rest_wf.bold_hmc_wf.mcflirt".
200408-18:18:18,877 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_OPTIMA4060_wf.func_preproc_task_rest_wf.bold_hmc_wf.normalize_motion" in "/nfsscratch/Users/ariveradompenciel/work/CRESTfmriprep/fmriprep_wf/single_subject_OPTIMA4060_wf/func_preproc_task_rest_wf/bold_hmc_wf/normalize_motion".
200408-18:18:19,104 nipype.workflow INFO:
	 [Node] Running "normalize_motion" ("niworkflows.interfaces.utils.NormalizeMotionParams")
200408-18:18:19,167 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_OPTIMA4060_wf.func_preproc_task_rest_wf.bold_hmc_wf.normalize_motion".
200408-18:18:22,230 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_OPTIMA4060_wf.func_preproc_task_rest_wf.bold_confounds_wf.fdisp" in "/nfsscratch/Users/ariveradompenciel/work/CRESTfmriprep/fmriprep_wf/single_subject_OPTIMA4060_wf/func_preproc_task_rest_wf/bold_confounds_wf/fdisp".
200408-18:18:22,243 nipype.workflow INFO:
	 [Node] Running "fdisp" ("nipype.algorithms.confounds.FramewiseDisplacement")
200408-18:18:22,269 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_OPTIMA4060_wf.func_preproc_task_rest_wf.bold_confounds_wf.fdisp".
200408-18:32:32,57 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_OPTIMA4060_wf.anat_preproc_wf.skullstrip_ants_wf.t1_skull_strip".
200408-18:32:32,895 nipype.workflow WARNING:
	 [Node] Error on "fmriprep_wf.single_subject_OPTIMA4060_wf.anat_preproc_wf.anat_derivatives_wf.ds_t1_preproc" (/nfsscratch/Users/ariveradompenciel/work/CRESTfmriprep/fmriprep_wf/single_subject_OPTIMA4060_wf/anat_preproc_wf/anat_derivatives_wf/ds_t1_preproc)
200408-18:32:32,915 nipype.workflow ERROR:
	 Node ds_t1_preproc failed to run on host argon-itf-cf45-27.hpc.
200408-18:32:34,708 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_OPTIMA4060_wf.func_preproc_task_rest_wf.bold_hmc_wf.fsl2itk" in "/nfsscratch/Users/ariveradompenciel/work/CRESTfmriprep/fmriprep_wf/single_subject_OPTIMA4060_wf/func_preproc_task_rest_wf/bold_hmc_wf/fsl2itk".
200408-18:32:34,732 nipype.workflow INFO:
	 [Node] Running "fsl2itk" ("fmriprep.interfaces.itk.MCFLIRT2ITK")
200408-18:33:28,596 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_OPTIMA4060_wf.func_preproc_task_rest_wf.bold_hmc_wf.fsl2itk".
```

### Error (stderr file)

```
/usr/local/miniconda/lib/python3.6/site-packages/bids/grabbids/__init__.py:6: FutureWarning: grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8
  warnings.warn("grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8", FutureWarning)
[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata.
  Falling back to 'CITATION'
/usr/local/miniconda/lib/python3.6/site-packages/bids/grabbids/__init__.py:6: FutureWarning: grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8
  warnings.warn("grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8", FutureWarning)
/usr/local/miniconda/lib/python3.6/site-packages/bids/layout/bids_layout.py:116: UserWarning: 'dataset_description.json' file is missing from project root. You may want to set the root path to a valid BIDS project.
  warnings.warn("'dataset_description.json' file is missing from "
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 308, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 522, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/bids.py", line 252, in _run_interface
    os.makedirs(out_path, exist_ok=True)
  File "/usr/local/miniconda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/miniconda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/miniconda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 1 more times]
  File "/usr/local/miniconda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/mnt/Projects'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/utils/filemanip.py", line 791, in makedirs
    os.makedirs(path)
  File "/usr/local/miniconda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/miniconda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/miniconda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 2 more times]
  File "/usr/local/miniconda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/mnt/Projects'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 342, in main
    fmriprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 595, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 184, in run
    self._send_procs_to_workers(updatehash=updatehash, graph=graph)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 316, in _send_procs_to_workers
    'traceback': traceback
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 225, in _clean_queue
    crashfile = self._report_crash(self.procs[jobid], result=result)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 209, in _report_crash
    return report_crash(node, traceback=tb)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/tools.py", line 49, in report_crash
    makedirs(crashdir, exist_ok=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/utils/filemanip.py", line 795, in makedirs
    raise OSError('Could not create directory %s' % path)
OSError: Could not create directory /mnt/Projects/CREST/derivatives/fmriprep/sub-OPTIMA4060/log/20200408-181636_935ebc88-48a6-4645-b4ca-5a561586e29c
```

**Comment by jdkent** [comment] 2020-04-09 14:33
duplicate of #11 (same permission error)

**Closed as completed by jdkent** 2020-04-09 14:33 UTC
Labels: fmriprep, singularity, argon
